- [[SFT: Selling an Idea]] #v1 [[roam/templates]] 
    - ![low-angle photography of brown gothic building interior](https://images.unsplash.com/photo-1531944213227-db53a6d0f3bd?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80)
        - Photo by [Matteo Kutufa](https://unsplash.com/@emmekappaphoto?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText) on [Unsplash](/s/photos/perspectives?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText)
    - __"The person sitting across from you is not you."__
        - -Brendan Langen
    - Roam allows you to have a ^^conversation^^ with yourself. This affords you the chance to [[think in layers]]. If this is your first time, **start here**! 
        - Hey, what's your name? 
            - __[write here]__
        - Cool. Let's work through your situation. First, what's the dream? If everything goes according to plan, what's your desired outcome? 
            - __[write here]__
        - Okay. Great. What do you feel is holding you back from achieving that? 
            - __[write here]__
        - How do you propose we solve this? 
            - __[write here]__
    - This will take 25 minutes of your time, or one ^^pomodoro^^. Ready? Click the tomato. 
        - {{[[POMO]]: 25}}
            - If you're ever curious why we use the pomodoro, trust the wiser folk below. 
                - https://twitter.com/andy_matuschak/status/1307075941177401346?lang=en
                - https://todoist.com/productivity-methods/pomodoro-technique#:~:text=The%20Pomodoro%20Technique%20helps%20you,you%20should%20be%20working%20on.
            - Each section has an accompanying pomodoro. Hit 'em all. 
    - First, we need to ^^change our environment^^. We can't jump into this session without putting ourselves in the right headspace. 
        - This will take 3 minutes - {{[[POMO]]: 3}}. 
            - Hit start.
        - Go run __cold water__ on your face. We'll wait. 
            - We need to engage the senses to best frame our thought.
        - Perfect. Now, let's __breathe __for one minute. Click this. https://www.youtube.com/watch?v=geqIdgtRYDo
        - __Music __changes our brain waves. For this session, start this album - {{[[video]]: https://www.youtube.com/watch?v=vNwYtllyt3Q.}} Don't worry. We won't lead you astray.
    - Now we're ready to go. We're going to look through the lens of other people. ^^Seek first to understand.^^
        - For this to go well, someone needs to say yes. Who is the key person you need to convince? 
            - Evan
        - Something you'll see throughout our work is the idea of [[concept, not copy]]. To go from 0 to 1, first we have to get the idea out. 
        - Start by summarizing, in 10 seconds. {{[[POMO]]: .166}}
            - What does success look like for__[write here]__? 
                - __[write here]__
                    - this is our base timescale - 10 seconds.
                        - then, 10 minutes.
                        - then, 10 days.
                        - then, 10 months.
                        - then, 10 years.
        - Nice. Now we can elaborate. Let's take 10 minutes to walk through an insightful **design framework**. {{[[POMO]]: 10}}
            - 1. Build on that last thought. How is__[write here]__'s success measured? 
                - I'm not sure...
                - if you need more context...
                    - We have to start with their top priority. What outcome does [name] hope to achieve? 
            - 2. What's stopping us right now? What do they think the biggest barrier is to achieving that? 
                - __[write here]__
                - if you need more context...
                    - Let's lay out the situation. We need to see how__[write here]__ thinks is holding us back from success.
            - 3. You have a hypothesis on how to solve this. What's your proposed solution?
                - __[write here]__
                - if you need more context...
                    - Inherently you have a plan. Let's lay out your initial thought. Don't worry. We'll return to this later.
            - 4. Fast forward - we did it. How does__[write here]__ feel? 
                - __[write here]__
                - if you need more context...
                    - This is the emotional job to be done. We're trying to empathize with what [name] cares about most, and what that will mean for how they feel should we achieve it. 
            - 5. Okay. How would this make other people feel about__[write here]__? Would this change the way they view them? How so? 
                - __[write here]__
                - if you need more context...
                    - This is the social job to be done. We're trying to think about the context we're in and how other people would react. This is usually a reputational sentiment. 
            - 6. How does__[write here]__ usually handle these things? What 'old way' of thinking are they stuck in?
                - __[write here]__
                - if you need more context...
                    - This is usually the point of friction. When situations like this have come up in the past, [name] usually handles them in a certain way. These are [their] habits.
            - 7. What usually holds us back from saying yes are anxieties. What worries would__[write here]__ have about this proposal? 
                - __[write here]__
                - if you need more context...
                    - What's stopping them fears or anxieties do [they] have from changing from their 'old ways'? What if our assumption is wrong? What if we screw this up? 
                        - What does [name] think could go wrong? 
                    - This should tie to [their] overall North Star. What do they care about most? 
                        - I like to do this via inversion - start with the end in mind and remove the misfits. 
            - 8. Where would__[write here]__see the most risk in this? 
                - __[write here]__
                - if you need more context...
                    - These are the objections that are voiced. If this is the first time you are doing something, an obvious objection is "Why do I think you can pull this off?" 
                    - Objections are public and usually quantitative. From a dollars-and-cents perspective, what would they say holds them back from saying yes?
            - 9. This is new to everyone. Where would__[write here]__see gaps in this? How can you compensate for these blindspots? 
                - __[write here]__
                - if you need more context...
                    - These are [name]'s internal doubts. Where might [they] lack confidence in this plan? 
                    - These are personal doubts based on their own capabilities. If this is the first big leap, they may lack the confidence they can pull it off. 
            - 10. What resources are currently lacking? How do you make this happen? 
                - __[write here]__
                - if you need more context...
                    - This is tied to resources - time, talent, and money. What do you need to do to make this happen? 
    - At the end of each session, we ^^reflect and summarize^^ the next steps. 
        - Throughout your experience, we'll talk about things in the scale of [[0, 1, 10]]. 
            - 0 is nothing. You have nothing to build atop. This does not pass our muster. 
                - In [[for thought]], you see these 0s come back until you have established a 1. We'll email you. :)
            - 1 is okay. You have a concept to build atop. This is a good start, but there's room to improve.
            - 10 is great. You have thought in layers and landed on something you are confident in. 
        - First, on a scale of [[0, 1, 10]], how **confident **are you in those answers about__[write here]__? {{[[POMO]]: 2}}
            - 1. Success Measure - __[write here]__
                - __[write here]__
            - 2. Barriers - __[write here]__
                - __[write here]__
            - 3. Your Hypothesis - __[write here]__
                - __[write here]__
            - 4. Emotional impact - __[write here]__
                - __[write here]__
            - 5. Social impact - __[write here]__
                - __[write here]__
            - 6. The 'old way' - __[write here]__
                - __[write here]__
            - 7. Anxieties - __[write here]__
                - __[write here]__
            - 8. Risks - __[write here]__
                - __[write here]__
            - 9. Blindspots - __[write here]__
                - __[write here]__
            - 10. Resources needed - __[write here]__
                - __[write here]__
        - Now, summarize and rate your hypothesis on the same [[0, 1, 10]] scale. How **good **do we think this is? {{[[POMO]]: 3}}
            - __[write here]__
        - Last step - when you come back to this later, what's your **next step**? How do you move this idea forward? {{[[POMO]]: 2}}
            - __[write here]__
    - That's it! 
        - ![multicolored fireworks at night](https://images.unsplash.com/photo-1564346793883-ca7b6f9044d6?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80)
            - Photo by [Josh Hild](https://unsplash.com/@joshhild?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText) on [Unsplash](/s/photos/brain-exploding?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText)
        - Did you finish within the pomodoro? 
            - __[Si o No]__
        - Did you enjoy this? Might as well use the 0, 1, 10 scale... ;) 
            - __[write here]__
        - How can this session improve for you? 
            - __[write here]__
    - You did great work today. You will appreciate this in the future. :) 
